import { Habit, TrackedDays } from '../types';

// IMPORTANT:
// 1. Create a new project at https://supabase.com/.
// 2. Go to the "SQL Editor" in your Supabase project dashboard.
// 3. Run the following SQL script to create the 'habits' table:
/*
  CREATE TABLE public.habits (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL DEFAULT 'My New Habit'::text,
    time text NOT NULL DEFAULT 'Anytime'::text,
    tracked_days jsonb NOT NULL DEFAULT '{}'::jsonb,
    start_date date NOT NULL DEFAULT now(),
    CONSTRAINT habits_pkey PRIMARY KEY (id)
  );
*/
// 4. Go to "Project Settings" > "API" and find your Project URL and anon public key.
// 5. Replace the placeholder values below with your actual Supabase URL and anon key.
//    In a real-world application, these should be stored in environment variables.

// Fix: Explicitly type constants as string to avoid TypeScript literal type inference errors when checking against placeholder values.
export const SUPABASE_URL: string = 'https://aogpnhhgdmngiqkruszw.supabase.co'; // Replace with your Supabase project URL
export const SUPABASE_ANON_KEY: string = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvZ3BuaGhnZG1uZ2lxa3J1c3p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1Mjg2MDQsImV4cCI6MjA3ODEwNDYwNH0.NeivvcgBRcBACjH0lADqGuxzydSKrP_R0QXb-p2Pj5E'; // Replace with your Supabase anon key

export const isSupabaseConfigured = () => {
  return SUPABASE_URL !== 'YOUR_SUPABASE_URL' && SUPABASE_ANON_KEY !== 'YOUR_SUPABASE_ANON_KEY';
};

if (SUPABASE_URL === 'YOUR_SUPABASE_URL') {
  console.error("Supabase URL is not configured. Please update it in services/supabaseService.ts");
}
if (SUPABASE_ANON_KEY === 'YOUR_SUPABASE_ANON_KEY') {
  console.error("Supabase anon key is not configured. Please update it in services/supabaseService.ts");
}


// @ts-ignore - supabase is loaded from CDN in index.html
const { createClient } = window.supabase;
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

export const getHabits = async (): Promise<Habit[]> => {
  const { data, error } = await supabase.from('habits').select('*').order('created_at', { ascending: true });
  if (error) {
    console.error('Error fetching habits:', error.message);
    console.error('Full Supabase error object:', JSON.stringify(error, null, 2));

    if (error.message.includes("relation \"public.habits\" does not exist")) {
        alert("CRITICAL ERROR: The 'habits' table does not exist. Please follow the setup instructions in 'services/supabaseService.ts' to create it.");
    } else if (error.message.includes("JWT") || error.message.includes("Unauthorized")) {
        alert("CRITICAL ERROR: Supabase authentication failed. Please check your Supabase URL and anon key in 'services/supabaseService.ts'.");
    } else {
        alert(`An error occurred while fetching habits: ${error.message}\n\nThis might be because Row Level Security (RLS) is enabled on your 'habits' table without a policy. Please check the updated setup instructions to disable RLS or create a policy.`);
    }
    return [];
  }
  return data as Habit[];
};

export const addHabit = async (habitName: string = "My New Habit", habitTime: string = "Anytime"): Promise<Habit | null> => {
  const startDate = new Date();
  const startDateString = `${startDate.getFullYear()}-${(startDate.getMonth() + 1).toString().padStart(2, '0')}-${startDate.getDate().toString().padStart(2, '0')}`;
  
  const { data, error } = await supabase
    .from('habits')
    .insert([{ name: habitName, time: habitTime, start_date: startDateString }])
    .select()
    .single();
  
  if (error) {
    console.error('Error adding habit:', error);
    return null;
  }
  return data as Habit;
};

export const updateHabit = async (id: number, updates: Partial<Pick<Habit, 'name' | 'time' | 'tracked_days'>>): Promise<Habit | null> => {
  const { data, error } = await supabase
    .from('habits')
    .update(updates)
    .eq('id', id)
    .select()
    .single();
  
  if (error) {
    console.error('Error updating habit:', error);
    return null;
  }
  return data as Habit;
};

export const deleteHabit = async (id: number): Promise<boolean> => {
  const { error } = await supabase.from('habits').delete().eq('id', id);
  if (error) {
    console.error('Error deleting habit:', error);
    return false;
  }
  return true;
};