import React from 'react';
import { LogoIcon } from './Icons';

const SupabaseSetup: React.FC = () => {
  return (
    <div className="fixed inset-0 bg-gray-100 flex items-center justify-center z-50 p-4 font-sans">
      <div className="bg-white rounded-lg shadow-2xl p-6 md:p-8 max-w-4xl w-full mx-auto border-t-4 border-orange-500 overflow-y-auto max-h-full">
        <div className="flex items-center gap-4 mb-6">
            <LogoIcon className="h-12 w-12 text-orange-500" />
            <h2 className="text-2xl font-bold text-gray-800">Supabase Configuration Required</h2>
        </div>
        <p className="text-gray-600 mb-6">
          Welcome to the <strong>90 Day Habit Tracker</strong>! To get started, you need to connect this app to your own free Supabase project. This is a one-time setup that takes about 5 minutes.
        </p>
        
        <div className="space-y-4 text-sm">
            <div className="p-4 bg-orange-50 rounded-lg border border-orange-200">
                <h3 className="font-bold text-orange-800 mb-2">Step 1: Create a Supabase Project</h3>
                <p className="text-orange-700">
                  First, head over to Supabase and create a new project.
                </p>
                <a href="https://supabase.com/dashboard/projects" target="_blank" rel="noopener noreferrer" className="inline-block mt-2 bg-orange-600 text-white font-semibold px-4 py-2 rounded-lg hover:bg-orange-700 transition-colors">
                    Create New Project &rarr;
                </a>
                <p className="text-orange-700 mt-2 text-xs">
                    You'll need to sign up or log in. The free plan is more than enough.
                </p>
            </div>

            <div className="p-4 bg-blue-50 rounded-lg border border-blue-200">
                <h3 className="font-bold text-blue-800 mb-2">Step 2: Create the 'habits' Table</h3>
                <p className="text-blue-700 mb-2">
                    Once your project is ready, navigate to the <strong>SQL Editor</strong> section. You can use the link below (just replace <code className="bg-blue-200 text-blue-900 px-1 py-0.5 rounded font-mono">[YOUR_PROJECT_ID]</code> with your project's ID from the URL).
                </p>
                <p className="text-blue-700 text-xs mb-2">
                  Example URL: <code className="bg-blue-200 text-blue-900 px-1 py-0.5 rounded font-mono">https://supabase.com/dashboard/project/abcdefg12345/sql/new</code>
                </p>
                <p className="text-blue-700">Click "+ New query" and paste in the entire script below to create the necessary database table.</p>
                <pre className="bg-gray-800 text-white p-3 rounded-md mt-2 text-xs overflow-x-auto font-mono">
{`-- This script creates the 'habits' table for your app.
CREATE TABLE public.habits (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL DEFAULT 'My New Habit'::text,
  time text NOT NULL DEFAULT 'Anytime'::text,
  tracked_days jsonb NOT NULL DEFAULT '{}'::jsonb,
  start_date date NOT NULL DEFAULT now(),
  CONSTRAINT habits_pkey PRIMARY KEY (id)
);`}
                </pre>
                <button onClick={() => navigator.clipboard.writeText(`CREATE TABLE public.habits (\n  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n  created_at timestamp with time zone NOT NULL DEFAULT now(),\n  name text NOT NULL DEFAULT 'My New Habit'::text,\n  time text NOT NULL DEFAULT 'Anytime'::text,\n  tracked_days jsonb NOT NULL DEFAULT '{}'::jsonb,\n  start_date date NOT NULL DEFAULT now(),\n  CONSTRAINT habits_pkey PRIMARY KEY (id)\n);`)} className="mt-2 bg-blue-600 text-white font-semibold px-3 py-1 rounded-lg hover:bg-blue-700 text-xs">
                  Copy SQL Script
                </button>
            </div>
            
            <div className="p-4 bg-yellow-50 rounded-lg border border-yellow-200">
                <h3 className="font-bold text-yellow-800 mb-2">Step 3: Disable Row Level Security (Important!)</h3>
                <p className="text-yellow-700 mb-2">
                    By default, Supabase protects your tables with Row Level Security (RLS). For this simple app, you need to disable it for the 'habits' table.
                </p>
                <ul className="list-disc list-inside text-yellow-700 my-2 space-y-1">
                    <li>Go to the <strong>Table Editor</strong> in your Supabase dashboard.</li>
                    <li>Select the <code className="bg-yellow-200 text-yellow-900 px-1 py-0.5 rounded font-mono">habits</code> table.</li>
                    <li>Above the data view, click the button that says <strong>"RLS is enabled"</strong> or find the "Enable Row Level Security" toggle in the table settings.</li>
                    <li>Click the toggle to <strong>disable</strong> it.</li>
                </ul>
                <p className="text-yellow-700 text-xs">
                    This step is crucial for the app to be able to read and write your habit data.
                </p>
            </div>

            <div className="p-4 bg-green-50 rounded-lg border border-green-200">
                <h3 className="font-bold text-green-800 mb-2">Step 4: Get Your API Keys & Update Code</h3>
                <p className="text-green-700 mb-2">
                    Next, go to your <strong>Project Settings &gt; API</strong>. Again, you can use the link below as a template.
                </p>
                 <p className="text-green-700 text-xs mb-2">
                  Example URL: <code className="bg-green-200 text-green-900 px-1 py-0.5 rounded font-mono">https://supabase.com/dashboard/project/abcdefg12345/settings/api</code>
                </p>
                <p className="text-green-700">On that page, you will find:</p>
                <ul className="list-disc list-inside text-green-700 my-2">
                    <li><strong>Project URL</strong></li>
                    <li><strong>Project API Keys</strong> (you need the <code className="bg-green-200 text-green-900 px-1 py-0.5 rounded font-mono">public</code> <code className="bg-green-200 text-green-900 px-1 py-0.5 rounded font-mono">anon</code> key)</li>
                </ul>
                 <p className="text-green-700">
                    Open the file <code className="bg-green-200 text-green-900 px-1 py-0.5 rounded font-mono">services/supabaseService.ts</code> in your code editor and replace the placeholder values with your actual URL and anon key.
                </p>
                <pre className="bg-gray-800 text-white p-3 rounded-md mt-2 text-xs overflow-x-auto font-mono">
{`// services/supabaseService.ts

// BEFORE
export const SUPABASE_URL = 'YOUR_SUPABASE_URL';
export const SUPABASE_ANON_KEY = 'YOUR_SUPABASE_ANON_KEY';

// AFTER (example)
export const SUPABASE_URL = 'https://abcdefg12345.supabase.co';
export const SUPABASE_ANON_KEY = 'ey....your-key....rw';`}
                </pre>
            </div>
             <div className="p-4 bg-purple-50 rounded-lg border border-purple-200">
                <h3 className="font-bold text-purple-800 mb-2">Step 5: Save & Reload</h3>
                <p className="text-purple-700">
                  Save your changes in <code className="bg-purple-200 text-purple-900 px-1 py-0.5 rounded font-mono">services/supabaseService.ts</code>. Once the file is saved, <strong>reload this page</strong>. The app will then be connected to your Supabase project.
                </p>
            </div>
        </div>

        <p className="mt-8 text-center text-gray-500 text-xs">
          This setup screen will disappear automatically once the Supabase URL and Key are correctly configured.
        </p>
      </div>
    </div>
  );
};

export default SupabaseSetup;